## MACRO
TARGET = smd.exe
AUTHORS =
LICENSE =
VERSION = 0.0001

MAKEFILE = Makefile
DC = dmd
MAKE = make
TO_COMPILE = src\sworks\smd\main.d src\sworks\base\aio.d src\sworks\base\array.d src\sworks\base\ctfe.d src\sworks\base\matrix.d src\sworks\base\traits.d src\sworks\svg.d src\sworks\util\cached_buffer.d src\sworks\win32\dump.d src\sworks\win32\gdi.d src\sworks\win32\port.d src\sworks\win32\single_window.d src\sworks\win32\svgr.d src\sworks\win32\util.d src\sworks\xml.d
TO_LINK = src\sworks\smd\main.obj src\sworks\base\aio.obj src\sworks\base\array.obj src\sworks\base\ctfe.obj src\sworks\base\matrix.obj src\sworks\base\traits.obj src\sworks\svg.obj src\sworks\util\cached_buffer.obj src\sworks\win32\dump.obj src\sworks\win32\gdi.obj src\sworks\win32\port.obj src\sworks\win32\single_window.obj src\sworks\win32\svgr.obj src\sworks\win32\util.obj src\sworks\xml.obj src\sworks\smd\resource.res
RC_FILE = src\sworks\smd\resource.rc
RES_FILE = src\sworks\smd\resource.res
COMPILE_FLAG = -m32mscoff -version=Unicode -version=WindowsVista -Jinclude -Isrc
LINK_FLAG = -m32mscoff
EXT_LIB =
FLAG =

## LINK COMMAND
$(TARGET) : $(TO_LINK) $(EXT_LIB)
	$(DC) -g $(LINK_FLAG) $(FLAG) -of$@ $**

## COMPILE RULE
.d.obj :
	$(DC) -c -g -op -debug $(COMPILE_FLAG) $(FLAG) $<
.rc.res :
	rc $<

## DEPENDENCE
$(TO_LINK) : $(MAKEFILE) $(EXT_LIB)
src\sworks\smd\main.obj : src\sworks\win32\svgr.d src\sworks\xml.d src\sworks\base\aio.d src\sworks\base\array.d src\sworks\win32\dump.d src\sworks\win32\util.d src\sworks\base\ctfe.d src\sworks\base\traits.d src\sworks\win32\gdi.d src\sworks\svg.d src\sworks\win32\port.d src\sworks\util\cached_buffer.d src\sworks\smd\main.d src\sworks\base\matrix.d src\sworks\win32\single_window.d
src\sworks\base\aio.obj : src\sworks\base\aio.d
src\sworks\base\array.obj : src\sworks\base\array.d
src\sworks\base\ctfe.obj : src\sworks\base\ctfe.d
src\sworks\base\matrix.obj : src\sworks\base\matrix.d
src\sworks\base\traits.obj : src\sworks\base\traits.d
src\sworks\svg.obj : src\sworks\xml.d src\sworks\base\aio.d src\sworks\base\ctfe.d src\sworks\svg.d src\sworks\base\traits.d src\sworks\util\cached_buffer.d src\sworks\base\matrix.d
src\sworks\util\cached_buffer.obj : src\sworks\base\traits.d src\sworks\util\cached_buffer.d src\sworks\base\aio.d
src\sworks\win32\dump.obj : src\sworks\base\array.d src\sworks\win32\util.d src\sworks\win32\single_window.d src\sworks\base\matrix.d src\sworks\win32\gdi.d src\sworks\win32\dump.d
src\sworks\win32\gdi.obj : src\sworks\win32\util.d src\sworks\base\matrix.d src\sworks\win32\gdi.d src\sworks\win32\dump.d
src\sworks\win32\port.obj : src\sworks\win32\port.d
src\sworks\win32\single_window.obj : src\sworks\win32\single_window.d
src\sworks\win32\svgr.obj : src\sworks\win32\single_window.d src\sworks\xml.d src\sworks\base\aio.d src\sworks\base\array.d src\sworks\win32\dump.d src\sworks\win32\util.d src\sworks\base\ctfe.d src\sworks\base\traits.d src\sworks\svg.d src\sworks\win32\gdi.d src\sworks\win32\port.d src\sworks\util\cached_buffer.d src\sworks\base\matrix.d src\sworks\win32\svgr.d
src\sworks\win32\util.obj : src\sworks\base\array.d src\sworks\win32\dump.d src\sworks\win32\util.d src\sworks\win32\gdi.d src\sworks\win32\port.d src\sworks\base\matrix.d src\sworks\win32\single_window.d
src\sworks\xml.obj : src\sworks\xml.d src\sworks\base\ctfe.d src\sworks\util\cached_buffer.d src\sworks\base\traits.d src\sworks\base\aio.d
src\sworks\smd\resource.res : src\sworks\smd\resource.rc

## PHONY TARGET
debug-all : $(RES_FILE)
	$(DC) -g -debug -of$(TARGET) $(COMPILE_FLAG) $(LINK_FLAG) $(TO_COMPILE) $(EXT_LIB) $(FLAG) $(RES_FILE)
release : $(RES_FILE)
	$(DC) -release -O -inline -of$(TARGET) $(COMPILE_FLAG) $(LINK_FLAG) $(TO_COMPILE) $(EXT_LIB) $(FLAG) $(RES_FILE)
clean :
	del $(TARGET) $(TO_LINK)
clean_obj :
	del $(TO_LINK)
vwrite :
	vwrite --setversion "$(VERSION)" $(TO_COMPILE)
ddoc :
	$(DC) -c -o- -op -D $(COMPILE_FLAG) $(DDOC_FILE) $(TO_COMPILE) $(FLAG)
	@type $(DOC_HEADER) $(DOC_FILES) $(DOC_FOOTER) > $(DOC_TARGET) 2>nul
	@del $(DOC_FILES)
show :
	@echo ROOT = src\sworks\smd\main.d
	@echo TARGET = $(TARGET)
	@echo VERSION = 0.0001
run :
	$(TARGET) $(FLAG)
edit :
	emacs $(TO_COMPILE) $(RC_FILE)
remake :
	amm -m32mscoff -version=Unicode -version=WindowsVista -Jinclude smd.exe .\src\sworks\smd\main.d v=0.0001 src\sworks\smd\resource.rc $(FLAG)

debug :
	ddbg $(TARGET)

## generated by amm.
readme:
	dmd -c -o- -D -Dfreadme.md -version=README src\sworks\smd\main.d doc\src\readme.ddoc

